version: '3'

services:
  db:
    build:
    context: .
      dockerfile: Dockerfile.mysql
    restart: always
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --socket=/tmp/mysql.sock
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: glory1121
      MYSQL_PASSWORD: glory1121
      MYSQL_DATABASE: root
      TZ: 'Asia/Tokyo'
    tty: true
    stdin_open: true

  app:
    build: .
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/CustomerCalender
      - public-data:/CustomerCalender/public
      - tmp-data:/CustomerCalender/tmp
      - log-data:/CustomerCalender/log
    environment: 
      TZ: 'Asia/Tokyo'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links: 
      - db


  web:
    build:
      context: containers/nginx
    ports:
      - 8080:80
    volumes:
      - public-data:/CustomerCalender/public
      - tmp-data:/CustomerCalender/tmp
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links: 
      - db
  


volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:


